services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:5000"
    environment:
      JAVA_HOME: "${{ secrets.JAVA_HOME }}"
      Keycloak_Audience: "${{ secrets.KEYCLOAK_AUDIENCE }}"
      Keycloak_Authority: "${{ secrets.KEYCLOAK_AUTHORITY }}"
      Keycloak_ClientId: "${{ secrets.KEYCLOAK_CLIENTID }}"
      Keycloak_Password: "${{ secrets.KEYCLOAK_PASSWORD }}"
      Keycloak_URL: "${{ secrets.KEYCLOAK_URL }}"
      Keycloak_Username: "${{ secrets.KEYCLOAK_USERNAME }}"
      KEYCLOAK_ADMIN: "${{ secrets.KEYCLOAK_ADMIN }}"
      KEYCLOAK_ADMIN_PASSWORD: "${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}"
      LibraryDatabase: "${{ secrets.LIBRARYDATABASE }}"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9002:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=${KEYCLOAK_BD_USERNAME}
      - KC_DB_PASSWORD=${KEYCLOAK_BD_PASSWORD}
    command: start-dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${KEYCLOAK_BD_USERNAME}
      - MYSQL_DATABASE=${KC_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql

volumes:
  mysql_data:
