services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__LibraryDatabase=Server=libraryorsdb-desofs.mysql.database.azure.com;Port=3306;Database=${MYSQL_DATABASE};User=${DB_USER}@libraryorsdb-desofs;Password=${DB_PASSWORD};SslMode=Required;
      - Keycloak__Authority=http://keycloak:8080/realms/library
      - Keycloak__Audience=library-client
      - Keycloak__ClientId=library-client
      - Keycloak__ClientSecret=${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://libraryorsdb-desofs.mysql.database.azure.com:3306/keycloak?useSSL=true&requireSSL=true
      - KC_DB_USERNAME=${DB_USER}@libraryorsdb-desofs
      - KC_DB_PASSWORD=${DB_PASSWORD}
    command: start-dev

