version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__LibraryDatabase=Server=mysql;Port=3306;Database=librarydb;User=root;Password=rootpassword;
      - Keycloak__Authority=http://keycloak:8080/auth/realms/library
      - Keycloak__Audience=library-client
      - Keycloak__ClientId=library-client
      - Keycloak__ClientSecret=your-client-secret
    depends_on:
      - mysql
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=rootpassword
    command: start-dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=librarydb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql

volumes:
  mysql_data: 