// <auto-generated />
using System;
using LibraryOnlineRentalSystem.Repository.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryOnlineRentalSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250521223538_AddHashedPasswordToUser")]
    partial class AddHashedPasswordToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LibraryOnlineRentalSystem.Domain.Book.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryOnlineRentalSystem.Domain.Role.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("39a5af91-1c9c-4932-b2d5-2cc2ceeaf41d"),
                            Description = "Administrator with full access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9f852c9c-02e4-41b6-b3b3-ebf1f4b821c0"),
                            Description = "Library manager with book management access",
                            Name = "LibraryManager"
                        },
                        new
                        {
                            Id = new Guid("003140f9-ad11-4312-bad8-3362ff740a77"),
                            Description = "Regular user with basic access",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("LibraryOnlineRentalSystem.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LibraryOnlineRentalSystem.Domain.Book.Book", b =>
                {
                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.AmountOfCopies", "AmountOfCopies", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("BookAmountOfCopies")
                                .HasColumnType("int");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.Author", "Author", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BookAuthor")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.Category", "Category", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BookCategoryName")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.Description", "Description", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BookDescription")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.ISBN", "Isbn", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BookISBN")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.Book.Publisher", "Publisher", b1 =>
                        {
                            b1.Property<string>("BookId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("PublisherName")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.Navigation("AmountOfCopies")
                        .IsRequired();

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Isbn")
                        .IsRequired();

                    b.Navigation("Publisher")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryOnlineRentalSystem.Domain.User.User", b =>
                {
                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.Biography", "Biography", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Biography");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.NIF", "Nif", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("TaxID")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("NIF");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LibraryOnlineRentalSystem.Domain.User.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("UserName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Biography")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Nif")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("UserName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
