name: Artifact Test

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello" > file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: file.txt

  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-artifact
      - run: cat file.txt
