name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Executa diariamente

env:
  PROJECT_DIR: ./LibraryOnlineRentalSystem
  CSPROJ_NAME: LibraryOnlineRentalSystem.csproj

jobs:
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify project structure
      run: |
        echo "Verificando estrutura em ${{ env.PROJECT_DIR }}"
        ls -la ${{ env.PROJECT_DIR }}
        test -f "${{ env.PROJECT_DIR }}/${{ env.CSPROJ_NAME }}" || {
          echo "::error::Arquivo ${{ env.CSPROJ_NAME }} não encontrado"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore ${{ env.CSPROJ_NAME }}
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Configurar Snyk
      uses: snyk/actions/setup@master
      with:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Verificar monitoramento Snyk
      run: snyk monitor
      working-directory: ${{ env.PROJECT_DIR }}
      continue-on-error: true

    - name: Scan de dependências (CSA)
      run: snyk test --file=${{ env.CSPROJ_NAME }} --all-projects
      working-directory: ${{ env.PROJECT_DIR }}
      continue-on-error: true
      
    - name: Scan de código (SAST)
      run: snyk code test --severity-threshold=high
      working-directory: ${{ env.PROJECT_DIR }}
      continue-on-error: true

    - name: Gerar relatório SARIF
      run: snyk code test --sarif-file-output=snyk.sarif
      working-directory: ${{ env.PROJECT_DIR }}
      if: always()

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ env.PROJECT_DIR }}/snyk.sarif
      if: always()