name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository (with proper authentication)
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN || github.token }}
        repository: ISEP-1190402/desofs2025_wed_pbs_3
        path: ./desofs2025_wed_pbs_3

    - name: Verify project structure
      working-directory: ./desofs2025_wed_pbs_3
      run: |
        echo "Verifying project structure"
        ls -la
        test -f "LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.csproj" || {
          echo "::error::Project file not found"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./desofs2025_wed_pbs_3/LibraryOnlineRentalSystem
      run: dotnet restore LibraryOnlineRentalSystem.csproj

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Run Snyk Scans
      working-directory: ./desofs2025_wed_pbs_3/LibraryOnlineRentalSystem
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk test --file=LibraryOnlineRentalSystem.csproj --all-projects --sarif-file-output=snyk-deps.sarif || true
        snyk code test --severity-threshold=high --sarif-file-output=snyk-code.sarif || true

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: |
          ./desofs2025_wed_pbs_3/LibraryOnlineRentalSystem/snyk-deps.sarif
          ./desofs2025_wed_pbs_3/LibraryOnlineRentalSystem/snyk-code.sarif
      if: always()