name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  PROJECT_DIR: ./LibraryOnlineRentalSystem
  CSPROJ_NAME: LibraryOnlineRentalSystem.csproj  # Alterado para apenas o nome do arquivo

jobs:
  security-scan:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify project structure
      run: |
        echo "Verifying project structure in ${{ env.PROJECT_DIR }}"
        ls -la ${{ env.PROJECT_DIR }}
        test -f "${{ env.PROJECT_DIR }}/${{ env.CSPROJ_NAME }}" || { echo "::error::Project file ${{ env.CSPROJ_NAME }} not found in ${{ env.PROJECT_DIR }}"; exit 1; }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.CSPROJ_NAME }}
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Install Snyk
      run: npm install -g snyk

    - name: Authenticate to Snyk
      run: snyk auth ${{ env.SNYK_TOKEN }}

    # CSA - Análise de segurança do código (dependências)
    - name: Run Snyk CSA (Dependency Scan)
      run: snyk test --file=${{ env.CSPROJ_NAME }} --all-projects
      working-directory: ${{ env.PROJECT_DIR }}
      continue-on-error: true
      
    # SAST - Teste estático de segurança do código
    - name: Run Snyk SAST (Code Analysis)
      run: snyk code test . --severity-threshold=high
      working-directory: ${{ env.PROJECT_DIR }}
      continue-on-error: true

    # Opcional: Gerar relatório SARIF para integração com GitHub Advanced Security
    - name: Generate SARIF report
      run: snyk code test . --sarif-file-output=snyk.sarif
      working-directory: ${{ env.PROJECT_DIR }}
      if: always()

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ env.PROJECT_DIR }}/snyk.sarif
      if: always()