name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: ./src

    - name: Verify project structure
      working-directory: ./src
      run: |
        echo "Verifying project structure"
        ls -la
        test -f "LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.csproj" || {
          echo "::error::Project file not found"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./src/LibraryOnlineRentalSystem
      run: dotnet restore

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Run Snyk Scans
      working-directory: ./src/LibraryOnlineRentalSystem
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        # Create directory for SARIF files if not exists
        mkdir -p ./snyk_results
        
        # Run scans and output to specific directory
        snyk test --file=LibraryOnlineRentalSystem.csproj --all-projects --sarif-file-output=./snyk_results/snyk-deps.sarif || true
        snyk code test --severity-threshold=high --sarif-file-output=./snyk_results/snyk-code.sarif || true
        
        # Verify SARIF files were created
        ls -la ./snyk_results/


    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: |
          ./src/LibraryOnlineRentalSystem/snyk_results/snyk-deps.sarif
          ./src/LibraryOnlineRentalSystem/snyk_results/snyk-code.sarif

    - name: Debug SARIF files
      run: |
       echo "Checking SARIF files..."
       find ./src -name "*.sarif" -exec ls -la {} \;
       find ./src -name "*.sarif" -exec head -n 5 {} \;
      if: always()      