name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_DIR: ./LibraryOnlineRentalSystem
  CSPROJ_NAME: LibraryOnlineRentalSystem.csproj

jobs:
  security-scan:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Necessário para upload de resultados SARIF
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify project structure
      run: |
        echo "Verifying project structure in ${{ env.PROJECT_DIR }}"
        ls -la ${{ env.PROJECT_DIR }}
        test -f "${{ env.PROJECT_DIR }}/${{ env.CSPROJ_NAME }}" || {
          echo "::error::Project file ${{ env.CSPROJ_NAME }} not found in ${{ env.PROJECT_DIR }}"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.CSPROJ_NAME }}
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Run Snyk Scans
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        # Dependency Scan
        snyk test --file=${{ env.CSPROJ_NAME }} --all-projects --sarif-file-output=snyk-deps.sarif || true
        
        # Code Scan
        snyk code test --severity-threshold=high --sarif-file-output=snyk-code.sarif || true
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: |
          ${{ env.PROJECT_DIR }}/snyk-deps.sarif
          ${{ env.PROJECT_DIR }}/snyk-code.sarif
      if: always()