name: OWASP ZAP DAST Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start application
        run: |
          dotnet build
          dotnet run --project LibraryOnlineRentalSystem &
          sleep 15  # tempo para o app subir (ajuste conforme necessário)

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:5000'  # Ajuste para a URL do seu app
          cmd_options: '-r zap_report.html'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
