name: Build and deploy - libraryrentalsystem to IIS (local runner)

on:
  push:
    branches: ["main"]   # ajuste se quiser outro branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: |
          cd LibraryOnlineRentalSystem
          dotnet build --configuration Release

      - name: Publish
        run: |
          dotnet publish LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.csproj -c Release -o ./publish

      - name: Deploy to IIS (LibraryOnlineRentalSystem)
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\LibraryOnlineRentalSystem\*" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force ./publish\* "C:\inetpub\wwwroot\LibraryOnlineRentalSystem\"
        shell: pwsh
