name: "Build and Deploy - Self Hosted"

on:
  workflow_dispatch:
    branches:
      - main  

env:
  WORKING_DIRECTORY: 'LibraryOnlineRentalSystem'
  DOTNET_VERSION: '8.0.x'          

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet publish --configuration Release --output 'published'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: '${{ env.WORKING_DIRECTORY }}/published'

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download new binaries over the top of the app
        uses: actions/download-artifact@v4
        with:
          name: application
          path: "c:/inetpub/wwwroot/LibraryOnlineRentalSystem"

