name: .NET

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore, Build and Test Main Project
      run: |
        dotnet restore LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln
        dotnet build LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln --configuration Release --no-restore
        dotnet test LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln --configuration Release --no-build --verbosity normal

    - name: Restore, Build and Test Tests Project
      run: |
        dotnet restore LibraryOnlineRentalSystem.Tests/LibraryOnlineRentalSystem.Tests.csproj
        dotnet build LibraryOnlineRentalSystem.Tests/LibraryOnlineRentalSystem.Tests.csproj --configuration Release --no-restore
        dotnet test LibraryOnlineRentalSystem.Tests/LibraryOnlineRentalSystem.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Lint the code 
      run: |
        dotnet new tool-manifest
        dotnet tool install JetBrains.ReSharper.GlobalTools
        dotnet tool restore
