name: .NET CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore LibraryOnlineRentalSystem.sln
      working-directory: LibraryOnlineRentalSystem

    - name: Build solution
      run: dotnet build LibraryOnlineRentalSystem.sln --configuration Release --no-restore
      working-directory: LibraryOnlineRentalSystem

    - name: Run tests
      run: dotnet test LibraryOnlineRentalSystem.sln --configuration Release --no-build --verbosity normal
      working-directory: LibraryOnlineRentalSystem
