name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln
    - name: Build
      run: dotnet build LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln --no-restore
    - name: Test
      run: dotnet test LibraryOnlineRentalSystem/LibraryOnlineRentalSystem.sln --no-build --verbosity normal
