name: .NET

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore LibraryOnlineRentalSystem.sln
      working-directory: LibraryOnlineRentalSystem
    - name: Build
      run: dotnet build LibraryOnlineRentalSystem.sln --no-restore
      working-directory: LibraryOnlineRentalSystem
    - name: Test
      run: dotnet test LibraryOnlineRentalSystem.sln --no-build --verbosity normal
      working-directory: LibraryOnlineRentalSystem
