name: Gitleaks Scan (Manual Cmd)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
            | grep "browser_download_url.*linux_amd64" \
            | cut -d '"' -f 4 \
            | xargs curl -L -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: |
          gitleaks detect --no-git --verbose --report-format sarif --report-path gitleaks-report.sarif
