name: Gitleaks Scan (Manual Cmd)

on:
  push:
    branches: [NF-98-gitleaks]
  pull_request:
    branches: [NF-98-gitleaks]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Extract Gitleaks v8.18.2
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz -o gitleaks.tar.gz
          mkdir gitleaks-bin
          tar -xzf gitleaks.tar.gz -C gitleaks-bin
          chmod +x gitleaks-bin/gitleaks

      - name: Run Gitleaks Scan
        run: |
          ./gitleaks-bin/gitleaks detect --no-git --verbose --report-format sarif --report-path gitleaks-report.sarif || true
