name: Gitleaks Scan (Manual Cmd)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, development]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Extract Gitleaks v8.18.2
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz -o gitleaks.tar.gz
          mkdir gitleaks-bin
          tar -xzf gitleaks.tar.gz -C gitleaks-bin
          chmod +x gitleaks-bin/gitleaks
      - name: Run Gitleaks Scan
        run: |
          ./gitleaks-bin/gitleaks detect --no-git --verbose --report-format sarif --report-path gitleaks-report.sarif || true
      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif-report
          path: gitleaks-report.sarif
