name: Gitleaks Scan (Manual Cmd)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Run Gitleaks
        run: |
          curl -L -o gitleaks https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64
          chmod +x gitleaks
          ./gitleaks detect --no-git --verbose --report-format sarif --report-path gitleaks-report.sarif
