name: Gitleaks Scan (Manual Cmd)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Extract Gitleaks v8.18.2
        run: |
          curl -L -o gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_windows_x64.zip

          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks

      - name: Run Gitleaks Scan
        run: |
          ./gitleaks detect --no-git --verbose --report-format sarif --report-path gitleaks-report.sarif
