name: .NET API Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: library-api
  API_PORT: 8080

jobs:
  security-scans:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1. Checkout (usando versão explícita)
      - name: Checkout
        uses: actions/checkout@v4.1.1  # Versão fixa

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.3.0  # Versão fixa
        with:
          dotnet-version: 8.0.x

      # 3. Build Docker
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      # 4. Inicia o container
      - name: Run API Container
        run: |
          docker run -d -p $API_PORT:$API_PORT --name api $DOCKER_IMAGE_NAME
          sleep 10

      # 5. SonarCloud (usando versão fixa)
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2.0.0  # Versão estável
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 6. OWASP ZAP Scan
      - name: API Security Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: http://localhost:$API_PORT
          args: -r
        timeout-minutes: 5

      # 7. Upload do relatório (usando v4, a mais recente)
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4.3.3  # Versão fixa
        with:
          name: zap-security-report
          path: zap-report.html

      # 8. Parar container
      - name: Stop Container
        if: always()
        run: docker stop api && docker rm api