name: Snyk SAST Code 

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  sast-scan:
    name: Run Snyk Code SAST 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: ./src

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Snyk CLI and PDF tools
      run: |
        npm install -g snyk@latest
        npm install -g puppeteer
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Create results directories
      working-directory: ./src
      run: |
        mkdir -p ./snyk_results/json
        mkdir -p ./snyk_results/sarif
        mkdir -p ./snyk_results/reports

    - name: Run Snyk Code SAST Scan
      working-directory: ./src
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        echo "Running Snyk static code analysis..."
        snyk code test --json > ./snyk_results/json/snyk-code.json || true
        snyk code test --sarif-file-output=./snyk_results/sarif/snyk-code.sarif || true

    - name: Create PDF report generator script
      run: |
        cat > ./src/generate_report.py << 'EOF'
        # (INSIRA AQUI O CÓDIGO PYTHON COMPLETO DO RELATÓRIO, MAS MANTENHA APENAS A PARTE DE "code_data")
        # Você pode reutilizar o script que já tem, simplificando para usar só `snyk-code.json`
        EOF

    - name: Generate PDF Report
      run: |
        python3 ./src/generate_report.py

    - name: Verify generated files
      run: |
        ls -la ./src/snyk_results/reports/
        file ./src/snyk_results/reports/security_report.pdf || echo "PDF not found"

    - name: Upload SAST Report Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: snyk-sast-reports
        path: |
          ./src/snyk_results/reports/
          ./src/snyk_results/json/
          ./src/snyk_results/sarif/

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./src/snyk_results/sarif/snyk-code.sarif
        category: snyk-code
      continue-on-error: true
      if: always()
