name: SAST Analysis (.NET + Snyk + Local Sonar Export)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PROJECT_DIR: ./LibraryOnlineRentalSystem

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_DIR }}/LibraryOnlineRentalSystem.csproj

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk (Code & Dependencies)
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          mkdir -p snyk_results
          snyk test --file=LibraryOnlineRentalSystem.csproj --all-projects --sarif-file-output=./snyk_results/snyk-deps.sarif || true
          snyk code test --severity-threshold=high --sarif-file-output=./snyk_results/snyk-code.sarif || true

      - name: Upload Snyk Reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: ${{ env.PROJECT_DIR }}/snyk_results/

      - name: Install SonarScanner CLI
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip -o -qq sonar-scanner-cli-5.0.1.3006-linux.zip || true
          mv sonar-scanner-5.0.1.3006 sonar-scanner

      - name: Generate Sonar Report Locally
        run: |
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=LibraryLocal \
            -Dsonar.sources=${{ env.PROJECT_DIR }} \
            -Dsonar.host.url=http://localhost \
            -Dsonar.login=dummy_token \
            -Dsonar.scm.disabled=true \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.projectName="LocalStaticAnalysis" || true

      - name: Upload Local Sonar Report Files
        run: |
          mkdir -p sonar_reports
          cp -r .scannerwork/* sonar_reports/ || true

      - name: Upload Sonar Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonar-local-report
          path: sonar_reports/
