name: OWASP ZAP Scan

on:
  release:
    types: [published]


jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://tek4geek.me/api/user'
          args: -r
